name: Mod Request
description: Recommend to add/remove a mod for Photon
labels: mod
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to suggest the addition/removal of a mod for Photon.
      Before you submit a request, please confirm that your request hasn't already been addressed [here](https://github.com/RealWTBking/photon/issues?q=is%3Aissue).

- type: input
  attributes:
    label: Modrinth link
    description: Paste the URL to the Modrinth page of the mod.
    placeholder: https://modrinth.com/mod/...
  validations:
    required: false

- type: input
  attributes:
    label: CurseForge link
    description: Paste the URL to the CurseForge page of the mod.
    placeholder: https://www.curseforge.com/minecraft/mc-mods/...
  validations:
    required: false

- type: input
  attributes:
    label: GitHub link
    description: Paste the URL to the GitHub repository of the mod.
    placeholder: https://github.com/...
  validations:
    required: false

- type: dropdown
  attributes:
    label: Channel Type
    description: Can be found on the Modrinth page of the mod.
    options:
    - Release
    - Beta
    - Alpha
    - I'm not sure / not on Modrinth
  validations:
    required: true

- type: dropdown
  attributes:
    label: License
    description: Located on the sidebar of the Modrinth page / GitHub repository of the mod.
    options:
    - All Rights Reserved (ARR)
    - Other
    - I'm not sure / not listed
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Confirm
    options:
    - label: This mod provides a performance increase to Minecraft. If the mod contains extra features that do not provide a performance increase, they can be disabled.
  validations:
    required: true

- type: textarea
  attributes:
    label: Mod Description
    description: In a concise manner, describe what the mod does.
  validations:
    required: true
