version = 3
defaultGlobalExecutorParallelismExpression = "\tmax(\r\n\t\t1,\r\n\t\tmin(\r\n\t\t\tif( is_windows,\r\n\t\t\t\t(cpus / 1.6 - 2),\r\n\t\t\t\t(cpus / 1.2 - 2)\r\n\t\t\t),\r\n\t\t\tif( is_j9vm,\r\n\t\t\t\t( ( mem_gb - (if(is_client, 0.6, 0.2)) ) / 0.5 ),\r\n\t\t\t\t( ( mem_gb - (if(is_client, 1.2, 0.6)) ) / 1.2 )\r\n\t\t\t)\r\n\t\t) - if(is_client, 2, 0)\r\n\t)"
globalExecutorParallelism = 1

[clientSideConfig]

	[clientSideConfig.modifyMaxVDConfig]
		enabled = false
		maxViewDistance = 32

[fixes]
	enforceSafeWorldRandomAccess = true

[noTickViewDistance]
	compatibilityMode = true
	maxConcurrentChunkLoads = 2
	ensureChunkCorrectness = false
	enabled = true

[generalOptimizations]
	midTickChunkTasksInterval = 100000
	optimizeAsyncChunkRequest = false

	[generalOptimizations.autoSave]
		mode = "ENHANCED"
		delay = 30000

[ioSystem]
	async = true
	# -1 for Vanilla default  
	# 1  for GZip (RFC1952) (Vanilla compatible) 
	# 2  for Zlib (RFC1950) (Vanilla default) (Vanilla compatible) 
	# 3  for Uncompressed (Fastest, but higher disk usage) (Vanilla compatible) 
	chunkStreamVersion = 2
	gcFreeChunkSerializer = false
	replaceImpl = false
	chunkDataCacheSoftLimit = 8192
	chunkDataCacheLimit = 32678

[threadedWorldGen]
	allowThreadedFeatures = false
	reduceLockRadius = false
	asyncScheduling = false
	enabled = "false"

[vanillaWorldGenOptimizations]
	optimizeAquifer = false
	useEndBiomeCache = false

