name: Auto Update

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at 12:00 a.m. UTC
  workflow_dispatch:
    # Manual trigger
    branches:
      - main

permissions:
  contents: write

jobs:
  auto_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0 # Full history

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install packwiz
        # Source: Maintained fork of '0_byte/packwiz' (Modrinth API rate limit handling) with merged commits from upstream ('packwiz/packwiz')
        run: go install github.com/RealWTBking/packwiz@91ef80f643979e854227e8ba83c8acd43b1d1595

      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: cd builder && bun install

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run auto_update
        env:
          MODRINTH_PAT_TOKEN: ${{ secrets.MODRINTH_PAT_TOKEN }}
          MODRINTH_PROJECT_ID: ${{ secrets.MODRINTH_PROJECT_ID }}
          MODRINTH_CLIENT_ID: ${{ secrets.MODRINTH_CLIENT_ID }}
          MODRINTH_CLIENT_SECRET: ${{ secrets.MODRINTH_CLIENT_SECRET }}
          NODE_ENV: production
        run: cd builder && bun run auto_update